"""empty message

Revision ID: f442d50488ba
Revises: 4bba099454bd
Create Date: 2021-01-06 23:02:22.678764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f442d50488ba'
down_revision = '4bba099454bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('daily_stamps')
    op.add_column('colors', sa.Column('title', sa.String(length=50), nullable=True))
    op.drop_constraint('colors_name_key', 'colors', type_='unique')
    op.create_unique_constraint(None, 'colors', ['title'])
    op.drop_column('colors', 'name')
    op.add_column('habits', sa.Column('icon_id', sa.Integer(), nullable=False))
    op.drop_constraint('habits_stamp_id_fkey', 'habits', type_='foreignkey')
    op.create_foreign_key(None, 'habits', 'icons', ['icon_id'], ['id'])
    op.drop_column('habits', 'stamp_id')
    op.add_column('programs', sa.Column('icon_id', sa.Integer(), nullable=False))
    op.add_column('programs', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_constraint('programs_stamp_id_fkey', 'programs', type_='foreignkey')
    op.create_foreign_key(None, 'programs', 'icons', ['icon_id'], ['id'])
    op.drop_column('programs', 'stamp_id')
    op.drop_column('programs', 'program')
    op.add_column('rewards', sa.Column('icon_id', sa.Integer(), nullable=False))
    op.add_column('rewards', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_constraint('rewards_stamp_id_fkey', 'rewards', type_='foreignkey')
    op.create_foreign_key(None, 'rewards', 'icons', ['icon_id'], ['id'])
    op.drop_column('rewards', 'stamp_id')
    op.drop_column('rewards', 'reward')
    op.add_column('stamps', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('stamps', sa.Column('habit_id', sa.Integer(), nullable=False))
    op.add_column('stamps', sa.Column('membership_id', sa.Integer(), nullable=False))
    op.add_column('stamps', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint('stamps_stamp_key', 'stamps', type_='unique')
    op.create_foreign_key(None, 'stamps', 'habits', ['habit_id'], ['id'])
    op.create_foreign_key(None, 'stamps', 'memberships', ['membership_id'], ['id'])
    op.drop_column('stamps', 'type')
    op.drop_column('stamps', 'stamp')
    op.add_column('users', sa.Column('icon_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_stamp_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'icons', ['icon_id'], ['id'])
    op.drop_column('users', 'stamp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stamp_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_stamp_id_fkey', 'users', 'stamps', ['stamp_id'], ['id'])
    op.drop_column('users', 'icon_id')
    op.add_column('stamps', sa.Column('stamp', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('stamps', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stamps', type_='foreignkey')
    op.drop_constraint(None, 'stamps', type_='foreignkey')
    op.create_unique_constraint('stamps_stamp_key', 'stamps', ['stamp'])
    op.drop_column('stamps', 'status')
    op.drop_column('stamps', 'membership_id')
    op.drop_column('stamps', 'habit_id')
    op.drop_column('stamps', 'date')
    op.add_column('rewards', sa.Column('reward', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('rewards', sa.Column('stamp_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.create_foreign_key('rewards_stamp_id_fkey', 'rewards', 'stamps', ['stamp_id'], ['id'])
    op.drop_column('rewards', 'title')
    op.drop_column('rewards', 'icon_id')
    op.add_column('programs', sa.Column('program', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('programs', sa.Column('stamp_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.create_foreign_key('programs_stamp_id_fkey', 'programs', 'stamps', ['stamp_id'], ['id'])
    op.drop_column('programs', 'title')
    op.drop_column('programs', 'icon_id')
    op.add_column('habits', sa.Column('stamp_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.create_foreign_key('habits_stamp_id_fkey', 'habits', 'stamps', ['stamp_id'], ['id'])
    op.drop_column('habits', 'icon_id')
    op.add_column('colors', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'colors', type_='unique')
    op.create_unique_constraint('colors_name_key', 'colors', ['name'])
    op.drop_column('colors', 'title')
    op.create_table('daily_stamps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('habit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('membership_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name='daily_stamps_habit_id_fkey'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name='daily_stamps_membership_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_stamps_pkey')
    )
    op.drop_table('icons')
    # ### end Alembic commands ###
