"""empty message

Revision ID: 2242667e33ac
Revises: 1285c7241bfb
Create Date: 2021-01-04 20:00:48.643955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2242667e33ac'
down_revision = '1285c7241bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stamps', sa.Column('membership_id', sa.Integer(), nullable=False))
    op.drop_constraint('daily_stamps_member_id_fkey', 'daily_stamps', type_='foreignkey')
    op.create_foreign_key(None, 'daily_stamps', 'memberships', ['membership_id'], ['id'])
    op.drop_column('daily_stamps', 'member_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stamps', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'daily_stamps', type_='foreignkey')
    op.create_foreign_key('daily_stamps_member_id_fkey', 'daily_stamps', 'memberships', ['member_id'], ['id'])
    op.drop_column('daily_stamps', 'membership_id')
    # ### end Alembic commands ###
