"""empty message

Revision ID: 5b5bd2e19495
Revises: 59fe0e673c98
Create Date: 2021-07-06 22:28:15.317379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5bd2e19495'
down_revision = '59fe0e673c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('has_shop', sa.Boolean(), nullable=True))
    op.alter_column('rewards', 'limit_per_member',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rewards', 'limit_per_member',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('programs', 'has_shop')
    # ### end Alembic commands ###
