"""empty message

Revision ID: 86b26e06804f
Revises: 6e06cb974576
Create Date: 2021-01-18 23:22:24.413613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86b26e06804f'
down_revision = '6e06cb974576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('aids_order', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('programs', sa.Column('private', sa.Boolean(), nullable=False))
    op.add_column('programs', sa.Column('rew_ids_order', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('users', sa.Column('pids_order', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('users', sa.Column('private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private')
    op.drop_column('users', 'pids_order')
    op.drop_column('programs', 'rew_ids_order')
    op.drop_column('programs', 'private')
    op.drop_column('programs', 'aids_order')
    # ### end Alembic commands ###
