"""empty message

Revision ID: 5f0a20b6e72d
Revises: a1a4688899b0
Create Date: 2021-03-23 08:52:48.694701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0a20b6e72d'
down_revision = 'a1a4688899b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('has_shop', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'has_shop')
    # ### end Alembic commands ###
